@startuml
'https://plantuml.com/class-diagram

class Commande {
    id : entier
    date : datetime
    client : client
}

class Client {
    id_client : entier
    nom : chaine
    rue : chaine
    code : postal
    ville : chaine
    numero_telephone : chaine
}

class Produit {
    id
}
@enduml